codecov:
  strict_yaml_branch: develop
  notify:
    require_ci_to_pass: no

coverage:
  range: "50...80"

ignore:
  - "3rd/**/*"
  - "app/**/*"
  - "test/*"
  - "test/**/*"

comment: false

github_checks:
  annotations: false
